name: Twistedfork
favicon: null
layout_spectrum: 0.20332205551676452
typography_spectrum: 0.1648141359910369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6331250523217022
  lightness: 0.005234241718426347
  saturation: 0.81311215297319
  rhythmicContrast: 0.9669109520036727
purpose: []
